name: gesture-transfer
channels:
- peterjc123
- menpo
- conda-forge
- defaults
dependencies:
- python=3.5.5
- pytorch=0.4
- scipy
- opencv3
- scikit-image
- scikit-learn
- pip:
  - dominate==2.3.1
  - git+https://github.com/pytorch/vision.git
  - Pillow==5.0.0
  - numpy==1.14.1
  - visdom==0.1.7